### PR TITLE
Ner

### PR DESCRIPTION
**Pull request by viviankou**
This PR is to merge the NER branch with the develop branch.

NER Result train on Conll2003 eng.train and test on eng.testa with 10 iterations:
processed 51578 tokens with 5942 phrases; found: 5810 phrases; correct: 5017.
num_NER_tags: 1376.00%; correct_tags: 50202.00%; tokens: 51578.00%; 
accuracy:  97.33%; precision:  86.35%; recall:  84.43%; FB1:  85.38
Total Training Time:  11307s

@jeticg @vista521 @anoopsarkar please review

### CODE REVIEW

**Comment by anoopsarkar** [comment]
I looked at the code a little and there are many things that can be improved. The main file ner_tagger consumes the training data quietly and the user has no idea what is happening at first. The messages do not use the logger. And there are many efficiency issues to be addressed.  

However, I feel like we should merge with develop and create one or two new issues to deal with these issues.

**Comment by jeticg** [comment]
@anoopsarkar It's ok. The stuff you mentioned are all included within our project pagehttps://github.com/sfu-natlang/glm-parser/projects/1.

**Comment by anoopsarkar** [comment]
ok. so I'll just merge this PR unless there are minor changes to be made before we merge. let me know.

**Comment by jeticg** [comment]
I think you can just merge it, so that Jerry and I can get started. If there's anything we'll fix it.

**Pull request merged**
