### PR TITLE
POS Tagger Spark Train

### PR DESCRIPTION
**Pull request by jeticg**
- Fixed a bug with weight vector, where loading doesn't work for glm_parser
- Fixed a bug with learner, where dumping weight vector might not work
- moved pos_decode to `src/evaluate/tagger_evaluator`
- moved pos_viterbi to `src/tagger/viterbi`
- moved pos_common to `src/data/pos_tagset_reader`
- renamed `src/parse` to `src/parser` for consistency
- renamed `src/learn` to `src/learner` for consistency
- added `tagger` option to pos_tagger, so the user can choose to use `viterbi` or `viterbi_pruning`

This commit has been tested on all three modes of pos_tagger and glm_parser. For the pos_tagger, I am not uploading my logs because the tests are all done on my own hadoop cluster, since the school cluster is down at the moment.

While spark train reduces training time significantly, I started the training on hadoop with 8 shards and sequential on linearb, by the time the first iteration was finished on linearb, the whole training process on hadoop had already been completed. However, the results from parallel train did suffered a significant accuracy drop to 0.851089106723. 

I will try to further improve the performance of spark train as well as trying to increase accuracy. Also, due to the fact that evaluation actually took about 6 hours, I will also look into implementing parallel evaluation.

### CODE REVIEW

**Comment by Travelinglight** [comment]
In pos/pos_viterbi.py, line 77: `if str(feat + (tag,)) in w_vector:`
the extra comma makes the result string also contain a comma. I concern that it may not match any items in `feat_vec`

I would suggest that we use tuples as key in feat_vec instead of strings to make it more fault-tolerant, so that the extra commas or spaces won't cause trouble.

**Comment by jeticg** [comment]
I wouldn't do that. This has been thoroughly checked and proven to be working just fine. Besides, where would the supposed commas and brackets come from anyway.

**Comment by anoopsarkar** [comment]
I don't understand the answer to the question by @Travelinglight -- it is possible that it is not getting a weight for some features if the key does not match.

We should wait until we can figure out why the accuracy drops so much. That is not what we expect from the analysis in the original paper that describes the distributed perceptron.

**Comment by jeticg** [comment]
Originally the keys in weight vectors are all strings, until Kingston changed them in the POS Tagger and WeightVector implementation to tuples, which caused the GLM Parser's vector loading to malfunction because the GLM Parser is not expecting the keys to be tuples.

What Kingston is suggesting is, I think, that the comma in `str(feat + (tag,))` will be treated as a character in the string, which is not true because it is only used to convert the string `tag` to a tuple with single element. There shouldn't be any extra commas and spaces either.

**Comment by jeticg** [comment]
@anoopsarkar I have identified the problem in our averaged perceptron parallel learning implementation. I tried so hard to earn that chocolate which you have promised, but so far I've no luck in that direction. Also, perceptron with 8 shards was able to achieve an accuracy of 0.960292638722; on linearb with 4 shards, the accuracy of perceptron is 0.969371290904; on linearb with sequential perceptron, accuracy is 0.972100964779, which is a little bit higher than averaged perceptron's sequential accuracy 0.9697.

I will get started on fixing the learner. But I think it might be better to do it on a separat branch called `fix/learner`, as the issue has nothing to do with `pos_spark_trian` nor `spark_evaluation`'s implementation.

**Comment by anoopsarkar** [comment]
can you explain what the issue / bug was?

**Comment by jeticg** [comment]
The iterative parameter mixing algorithm was in fact a slightly modified parameter mixing algorithm, which the later basically combines all the w_vectors from each shards by the end of the last iteration, when the former combines at the end of each iteration. Our perceptron learner followed this principle so that it functioned as expected, but our averaged perceptron parallel learner wasn't. 

Averaged perceptron takes into the account the performance of the current w_vector by recording the number of sentences that it predicted correctly, every time we update the w_vector we multiply the difference between gold_vector and local_vector with that number and then add it into w_vector to preserve that good performance by that vector, and at the end of the final iteration divide it by the total number of sentences: 
`w_vector += (sentence_number_of_last_update - current_sentence_number) / total_number_of_sentences * (gold_vector - local_vector)`;
while in perceptron we just do:
`w_vector += gold_vector - local_vector`

But in our parallel learner implementation, averaged perceptron learner is not recording that number `sentence_number_of_last_update - current_sentence_number`, instead it is actually doing the same thing as perceptron, except that the final w_vector we are getting is actually the difference between before and after the final iteration. In short, our parallel averaged perceptron is just totally wrong.

**Comment by jeticg** [comment]
Oh wait, I think I've got it wrong.

**Comment by jeticg** [comment]
I'll come back after I've done more tests. The comments yesterday were mistakes, the code looks to be correct but there are a few problems that I still have doubts.

**Comment by jeticg** [comment]
@anoopsarkar I have committed my fix to a new branch called `fix/averaged-perceptron-parallel-learner-fix`.

Before my fix, the sum of all of the w_vectors on all shards are gathered by the end of each iteration, this part is fine. The problem was that it actually passes this sum to each shard again, which causes the sum of w_vectors from previous iterations to be duplicated, which means these earlier not-so-well-trained w_vectors are carrying more weight in the final result. This issue is barely noticeable while one simply look at the tests results when:
1. the total number of iterations is too small; or
2. the dataset used for training is too small; or
3. the number of shards we are using is too small.

In fact, the original averaged perceptron did quite well on tagging with the entire penn2malt dataset with 4 shards 5 iterations, it achieved 0.968067236178. Because we never did a full test with perceptron, one couldn't realise that perceptron actually did better with 0.969371290904 with the exact same configurations.

I am currently testing averaged perceptron tagging on penn2malt with 4 shards 5 iterations in standalone mode on linearb, and I'll do another test on yarn mode if I don't find any other problem.

I was unable to run glm_parser on entire penn2malt in yarn mode on my own cluster because it seems that either WeightVector or Ceisener implementation were too memory demanding, even linearb wasn't able to handle that in spark standalone mode. I will create a separate issue on the matter.

**Comment by anoopsarkar** [comment]
perceptron does as well as avg perceptron because it is also averaging at end of each epoch. this is to be expected. we might need to be aware of zeros in the vector or some data structure trick to avoid memory issues.

**Comment by jeticg** [comment]
The memory issue only exists in parallel train, and I was unable to tackle this on my own. Maybe it would be better to just wait for Andrei's new hvector, because I also noticed that sometimes our mydefaultdict might be significantly slower than python's native dict when doing specific tasks.

**Comment by jeticg** [comment]
The only thing that I am certain of is that our learners rarely do anything directly to hvector(which appears as WeightVector), mostly it just calls WeightVector methods.

**Comment by anoopsarkar** [comment]
memory usage in spark yarn mode should be no more than sequential mode, right?

**Comment by jeticg** [comment]
In theory, yes. There's no reason why it should require significantly more resources that is enough to crash my cluster in yarn mode and linearb in standalone mode. I think maybe in spark the memory management part didn't work that well with cython implemented classes, that's the only theory I could come up with so far.

**Comment by jeticg** [comment]
As changes are now being merged in another pull request(#59), I'll hereby close this one.

**Pull request closed without merging**
