### PR TITLE
autolog bash script added

### PR DESCRIPTION
**Pull request by Travelinglight**
`autolog.sh` created to do the following things:

1. Writing environment info (machine, Python version, Cython version) into a formatted log file.
2. Extracting configuration info (learner, parser, fgen, data, etc.) from `glm-parser.log` (raw log file) and write it into the formatted log file.
3. Extracting results from the raw log file and append it to the formatted log file.
4. clone the wiki repo, move the formatted log file into it, commit and remove the repo.

The usage could be find at the beginning of `autolog.sh`

### CODE REVIEW

**Comment by jeticg** [comment]
Should have done exactly the same thing with pos_tagger. The script is supposed to be shared by pos_tagger and glm_parser.

**Comment by anoopsarkar** [comment]
rename to proc_log.sh

**Comment by anoopsarkar** [comment]
Any objections to merging this PR? I seem to have lost track of this PR.

**Comment by Travelinglight** [comment]
I don't have objection.

**Pull request merged**
