### PR TITLE
Improve consistency of WeightVector usage

### PR DESCRIPTION
**Pull request by avacariu**
Since all that WeightVector is doing is holding a hvector defaultdict instance as an attribute and wrapping some of the `__methods__`, it should be a subclass of defaultdict. This change also allows it to be used as a defaultdict instead of other pieces of code accessing its `.data_dict` attribute directly (which sort of defeated the point of having the wrapper class).

This changes the interface of the WeightVector class, and I've fixed all the places where `.data_dict` was accessed directly, but if anyone's working on code that accesses `.data_dict`, remove that access and just use `w_vector` instead.

### CODE REVIEW

**Comment by anoopsarkar** [comment]
did you test it out on penn treebank? could you add in a log file directory that shows that the performance is unchanged?

**Comment by avacariu** [comment]
Performance meaning accuracy or running time?

**Comment by anoopsarkar** [comment]
just accuracy. we should probably incorporate running time in the logs in the (near) future but we are not there yet.

**Comment by avacariu** [comment]
Before this commit (949bb4c1a41497f5730a2132af606b82026dec3b):
```
Unlabeled accuracy: 0.865941551834
Unlabeled attachment accuracy: 0.871303458342
```

After this commit:
```
Unlabeled accuracy: 0.865941551834
Unlabeled attachment accuracy: 0.871303458342
```
So this change doesn't affect accuracy.

Tested using:
```
python glm_parser.py -i 1 -p /cs/natlang-user/vivian/penn-wsj-deps/ \
    --train='wsj_0[2-9][0-9][0-9].mrg.3.pa.gs.tab|wsj_1[0-9][0-9][0-9].mrg.3.pa.gs.tab|wsj_2[0-1][0-9][0-9].mrg.3.pa.gs.tab' \
    --test='wsj_0[0-1][0-9][0-9].mrg.3.pa.gs.tab|wsj_22[0-9][0-9].mrg.3.pa.gs.tab|wsj_24[0-9][0-9].mrg.3.pa.gs.tab' \
    --learner=perceptron \
    --fgen=english_1st_fgen \
    --parser=ceisner \
    --format=${project_path}/src/format/penn2malt.format
```
since I completely forgot about the now config files.

I've added a log file, but there's nothing to really compare it against since the previous tests are all slightly different.

**Pull request merged**
