### PR TITLE
Using POS Tagger in GLM Parser

### PR DESCRIPTION
**Pull request by jeticg**
This branch gives the glm_parser the ability to use the our pos_tagger to do the tagging while evaluating. Several bug fixes for develop branch are also included.
It also fixed the POS_Tagger in develop branch, it contained minor bugs that has been preventing its successful run.
This commit as of this moment has been tested in all three modes and proven to be working. I believe it is ready to be merged into develop.

### CODE REVIEW

**Comment by anoopsarkar** [comment]
Code review needed. @avacariu can you do it?

**Comment by avacariu** [comment]
Sure, I'll look at it

**Comment by avacariu** [comment]
@jeticg Regarding 163d220: Do we need to have all config files contain that option, or would it be sufficient to only have it in `default.config`?

**Comment by Travelinglight** [comment]
After pos-parser-merge-step-1 is merged into develop, there are 2 modes to run the glm-parser: using gold POS tags or using the tagger. If `tagger_w_vector` is None, gold POS tags are used, otherwise, the tagger is called. So it's necessary for each config file to have this option.

**Comment by avacariu** [comment]
I thought the point of `default.config` was to specify defaults so that they can be omitted from the language-specific config files. So if `default.config` had `tagger_w_vector =`, then if the option is omitted from the language-specific config file, you'd still have `config_parser.get('option', 'tagger_w_vector') == ''`

**Comment by jeticg** [comment]
Not exactly. default.config is used for conducting default tests with a relatively small dataset selected by our predecessors. Having it as default value storage device would be impractical because it cannot be automatically uploaded to Hadoop to be read.

**Comment by avacariu** [comment]
Alright, we can skip over that for now, and maybe look into initializing the config parser as `SafeConfigParser(os.environ + config)` in the future to avoid having to have empty options in the config files (I mean `+` conceptually, since I realize that's not a valid operation on dicts*)

\* As an aside, if anyone's interested in the various ways of merging 2 Python dicts into a new one for exactly this situation, this exists: http://treyhunner.com/2016/02/how-to-merge-dictionaries-in-python/

**Comment by avacariu** [comment]
These are general comments on the series of commits as a whole since I'm looking at a squashed commit of all of them instead of reading each one individually. A few of the comments are not specific to this PR, but I just noticed them while looking at the diff.

* there are a quite a few places where `print` is used instead of the logging module
* `DataPrep.dataPath` should probably be renamed to `DataPrep.data_uri` since it now seems to require a protocol prefix (i.e. `file://`).
* `self.dataPath[:7] != "file://"` -> `self.data_uri.startswith("file://")`. There are a bunch of places where this occurs.
* in `file_io.py`, `aRdd = aRdd.map(lambda x: str(x)).cache()`, you should be able to just pass in `str` instead of the lambda.
* I realize this wasn't added in this PR, but the modification `sys.path` at the top of `sentence.py` is _very_ hacky especially since `inspect.currentframe()` isn't guaranteed to work in all implementations of Python. The path can be modified using environment variables if we need to. (This is for the future, don't fix it now, but I noticed it in a few places).
* in `sentence.py`, there's a `if "HEAD" not in self.column_list.keys()` (and similar lines in another couple places in the file). This can be `if "HEAD" not in self.column_list`, which avoids a call to `keys()` (which is fairly slow because it has to build a new list, return it, and then run `__contains__()` on it which is O(n))
* also not added in this PR, but should be fixed at some point, `column_list` isn't a list, so it should be renamed to something more accurate.
* in `sentence.py` in `set_pos_list()`, it's checking if `column_list` has a certain key and then runs `sys.exit()` if it doesn't. I'd suggest that should be an exception instead since it'd be kind of surprising for someone using this toolkit if they call a function and it causes their program to crash without being able to catch the error.
* the same issue above is in `feature_generator_base.pyx`
* regarding the 2 points above: since something is being assigned to the `POSTAG` attribute/key and overwriting whatever was there before, it's not clear why it matters that there _was_ anything there before. A comment explaining the rationale would probably help clarify what's going on.
* there are some places where `sys.stderr.write()` is used, and that should be replaced with `logging.error()` (or `logger.error()` if `logger = logging.getLogger()`)
* `from X import *` should be avoided since it becomes unclear where functions / variables are coming from
* another general note since I noticed the removal of some files ending in `~`, we should add `*~` to the `.gitignore`
* there are quite a few places in the code where camel case function/variable names are used instead of snake case. I think for consistency and predictability, we should stick to snake case.
* I like the removal of the trailing whitespace in a few of the files :+1:. I have vim highlighting trailing whitespace in red, so sometimes files look like they're bleeding :stuck_out_tongue: 

That's it from me! I haven't actually run the code, and I've gotta head out right now, so the above is just based on me reading the diff of the PR. So other than the comments above, LGTM :+1:

**Comment by jeticg** [comment]
A lot of the code mentioned here haven't really been even scratched by either me or Kingston yet, some of the issues I am addressing them in my branch `pos_spark_train` now since I have finally started working on the feature generators and this sentence class and data pool mentioned here, including issue No.6-No.10. I would rather not do them all here because I have already started on `pos_spark_train`. 
1. Issue No.1 needs to be put on hold because if I don't use `print` there's no way for me to get any feedbacks when I am running the programme in yarn mode. Until we've come up with something I am afraid there's little I can do.
2. I will start working on No.2-No.5.
3. No.11, I haven't really taken any look into the error logging thing. It might be better to have someone address this on a separate branch, just to make sure any error actually gets posted into hadoop's error reporting files. Personally I suggest we make a new issue, for I do think it could involve a lot of testing which might take a bit more than a few hours of work.
4. I am addressing No.12 and No.14 in `src/data/*`, `src/feature/*`, `src/pos/*`, as well as `src/pos_tagger.py` in branch `pos_spark_train`. For the rest, I really can't spare that many time doing all those tests.

P.S, about tests. Currently in order to make sure everything could at least work without failure with the standard usage(that is where one does read the readme file carefully and not do anything unexpected), every time I make some changes I will run a complete test against affected modules, usually including but not limited to running tests on all three modes: `sequential`, `spark standalone`, `spark yarn mode`, two learning modules: `perceptron` and `average_perceptron`, and two tagger options: with tagger-w-vector` and without, so that's 12 tests plus a lot of other individual module tests, because some of my changes does affect a lot of components so I have to be as thorough as I could. I should have brought this up during our meeting today but I could use some help with these testing and debugging.

**Comment by Travelinglight** [comment]
I find `logging` doesn't print log on screen. If we want to do so, we need to define a logger and add a handler to it. So it would be `logger.info()` instead of `logging.info()`. Is that what we want?

**Comment by avacariu** [comment]
The reason `logging.info()` doesn't print to the screen is because the default logging level is `WARNING`, so you need to set `logging.basicConfig(level=logging.INFO)`.

Ideally, though, we want to use a logger because that'll allow us to add multiple handlers to it.

**Comment by Travelinglight** [comment]
OK I'm now adding loggers

**Comment by jeticg** [comment]
Make sure you run tests on Hadoop before commit.

**Comment by jeticg** [comment]
I will be fixing No.1-No.5 in this branch, and No.6-No.10 will be fixed in my pos_spark_train branch. No.11-No.13 in this branch. Personally I believe No.14 will have to wait for the general code review on develop branch, because I really don't think adopting snake cases would be a wiser decision over camel cases.

**Comment by anoopsarkar** [comment]
We can limit our testing to average_perceptron and test the perceptron learner only during a major merge (e.g. when we merge to master).

**Comment by jeticg** [comment]
The reason we might want to test perceptron every time we make changes that might affect it is because sometimes there might be bugs. It's not as important as averaged perceptron learner, but never the less it should be at least useable.

**Comment by anoopsarkar** [comment]
Yeah, along those lines I was thinking of this idea: merging perceptron and average_perceptron so that it goes through both code paths and then for runtime efficiency we can add a flag that runs just the average perceptron to save space and/or time.

**Comment by anoopsarkar** [comment]
ok. so to resolve this. let us test both perc and avg_perc for now until we do the merge I propose above.

**Comment by jeticg** [comment]
I have finished my fix in accordance with the code review above.
No.1-No.4 fixed;
No.5 Leave it;
No.6-No.10 as mentioned in my earlier comments, since these problems have been there for a long time and I am addressing them in my branch `pos_spark_train`, it would be better to leave them here for the time being;
No.11-No.13 fixed;
No.14 I don't think we should do this here. It involves a lot of files. We can figure it out when we are doing a code review on develop branch.

**Pull request merged**
