### PR TITLE
 Add docs/development.md file with development model and git tips

### PR DESCRIPTION
**Pull request by avacariu**
This is the initial version of this document. Thoughts?

### CODE REVIEW

**Comment by anoopsarkar** [comment]
Looks good.

One comment: Is there a way to avoid force-push altogether?

**Comment by avacariu** [comment]
If the committer doesn't push their commits until they're done (i.e. they clean up the history first), then they shouldn't need to force-push.

I'll clarify that in the Code Reviews section, and suggest creating a new branch instead of force-pushing if they've already pushed their changes. I'd like to leave the "Force-pushing safely" section in, though, as a general git tip for when there's no other option.

**Comment by anoopsarkar** [comment]
Just emphasize the "no other option". I read the rest of it and it looks good. 

One more question: you said "master" and "develop" were protected from unfortunate merges. How are they protected right now?

**Comment by avacariu** [comment]
They're not yet, but I figure it'd be a good idea if they were, so I put that in. There's a "Protected branches" section in the GitHub repo's settings where you can disable force-pushes for the branch and require status checks before merging into it.

**Comment by anoopsarkar** [comment]
Let's go ahead and set that up. Can you do it?

**Comment by avacariu** [comment]
I think only the repository owner can change settings. I don't see a "Settings" tab at all for this repo.

**Comment by anoopsarkar** [comment]
I've protected develop and master. Only I can push to them under current settings. So I assume I will have to do the Pull Request merges. It also will only allow push to develop if the branch to be merged has all the commits from develop (same settings for master).

**Comment by avacariu** [comment]
I've made the changes regarding force-pushing, and suggested creating new branches or just adding new commits as alternatives.

**Pull request merged**
