### PR TITLE
pos_spark_train & feature/spark-evaluator & fix/averaged-perceptron-parallel-learner-fix & feature/api-clean-up

### PR DESCRIPTION
**Pull request by jeticg**
This pull request contains work from the following branches:
- pos_spark_train
- feature/spark-evaluator
- fix/averaged-perceptron-parallel-learner-fix
- feature/api-clean-up

### Changes in pos_spark_train:

- Fixed a bug with weight vector, where loading doesn't work for glm_parser
- Fixed a bug with learner, where dumping weight vector might not work
- moved pos_decode to `src/evaluate/tagger_evaluator`
- moved pos_viterbi to `src/tagger/viterbi`
- moved pos_common to `src/data/pos_tagset_reader`
- renamed `src/parse` to `src/parser` for consistency
- renamed `src/learn` to `src/learner` for consistency
- added `tagger` option to pos_tagger, so the user can choose to use `viterbi` or `viterbi_pruning`

This branch has been tested on all three modes of pos_tagger and glm_parser. For the pos_tagger, I am not uploading my logs because the tests are all done on my own hadoop cluster, since the school cluster is down at the moment.

### Changes in feature/spark-evaluator

- restructured the evaluators, so that they all use the same structure provided in evaluator/__init__.py. Note that this will be changed when I am writing the API documents.
- bug fix with dumping w_vector in HDFS
- new config files for tagger. Taggers now uses config files starting with `pos_`
- added Viterbi pruning
- new testing scripts

This branch has been tested on all three modes of pos_tagger and glm_parser.

### Changes in fix/averaged-perceptron-parallel-learner-fix

- fixed the averaged parallel learner. It was incorrectly implemented which leads to a dramatic decrease of accuracy when training with more shards and iterations.
- fixed Eisner parser.

### Changes in feature/api-clean-up
- cleaned up apis, created docs for Learners, GLM Parsers, POS Taggers, Evaluators, DataPool and DataPrep

This branch has been tested on all three modes of pos_tagger and glm_parser.

### CODE REVIEW

**Comment by anoopsarkar** [comment]
are we sure that the renaming of `src/parse` and `src/learn` does not affect any other module in the glm-parser codebase?

**Comment by jeticg** [comment]
I checked quite thoroughly, replaced all references of the old names, and did a lot of testing. I am quite sure it won't go wrong.

**Comment by anoopsarkar** [comment]
Can I get a volunteer to do a code review for this PR? Github seems to have rolled out some fancy new code review tools to make this easier.

**Comment by jeticg** [comment]
@anoop vivian is doing it

**Pull request merged**
